/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pixelartrecover;

import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author erhannis
 */
public class PARMain extends javax.swing.JFrame {
    public BufferedImage imageSource;
    public BufferedImage imageTrueDest;
    public BufferedImage imageDest;
    public ImagePanel panelSource;
    public ImagePanel panelDest;
    
    /**
     * Creates new form PARMain
     */
    public PARMain() {
        setTitle("PixelArtRecover");
        initComponents();
        
        panelSource = new ImagePanel();
        panelDest = new ImagePanel();
        
        jScrollPane1.setViewportView(panelSource);
        jScrollPane3.setViewportView(panelDest);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        spinOffsetX = new javax.swing.JSpinner();
        spinOffsetY = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        spinStepX = new javax.swing.JSpinner();
        spinStepY = new javax.swing.JSpinner();
        btnPixelize = new javax.swing.JButton();
        jSplitPane2 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mitemOpenSource = new javax.swing.JMenuItem();
        mitemSaveDest = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(150);

        jLabel1.setText("Offets");

        spinOffsetX.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        spinOffsetY.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        jLabel2.setText("Step Size");

        spinStepX.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        spinStepY.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        btnPixelize.setText("Pixelize");
        btnPixelize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPixelizeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(spinOffsetX, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinOffsetY, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(spinStepX, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinStepY, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPixelize))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spinOffsetX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spinOffsetY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spinStepX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spinStepY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(btnPixelize)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jSplitPane2.setDividerLocation(140);
        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane2.setResizeWeight(0.5);
        jSplitPane2.setTopComponent(jScrollPane1);
        jSplitPane2.setRightComponent(jScrollPane3);

        jSplitPane1.setRightComponent(jSplitPane2);

        jMenu1.setText("File");

        mitemOpenSource.setText("Open source...");
        mitemOpenSource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemOpenSourceActionPerformed(evt);
            }
        });
        jMenu1.add(mitemOpenSource);

        mitemSaveDest.setText("Save dest...");
        mitemSaveDest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemSaveDestActionPerformed(evt);
            }
        });
        jMenu1.add(mitemSaveDest);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem1.setText("Explanation");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JFileChooser fileChooser = new JFileChooser();
    
    private void mitemSaveDestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemSaveDestActionPerformed
        if (fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                File file = fileChooser.getSelectedFile();
                ImageIO.write(imageTrueDest, "PNG", file);
            } catch (IOException ex) {
                Logger.getLogger(PARMain.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Error saving image");
            }
        }
    }//GEN-LAST:event_mitemSaveDestActionPerformed

    private void mitemOpenSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemOpenSourceActionPerformed
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                File file = fileChooser.getSelectedFile();
                BufferedImage bi = ImageIO.read(file);
                imageSource = bi;
                panelSource.setImage(imageSource);
            } catch (IOException ex) {
                Logger.getLogger(PARMain.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Error opening image");
            }
        }
    }//GEN-LAST:event_mitemOpenSourceActionPerformed

    private void btnPixelizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPixelizeActionPerformed
        if (imageSource != null) {
            int offsetX = (Integer)spinOffsetX.getValue();
            int offsetY = (Integer)spinOffsetY.getValue();
            int stepX = (Integer)spinStepX.getValue();
            int stepY = (Integer)spinStepY.getValue();
            BufferedImage dest = new BufferedImage((imageSource.getWidth() - offsetX + stepX - 1) / stepX, (imageSource.getHeight() - offsetY + stepY - 1) / stepY, BufferedImage.TYPE_INT_ARGB);
            int destX = 0;
            int destY = 0;
            for (int x = offsetX; x < imageSource.getWidth(); x += stepX, destX++) {
                for (int y = offsetY; y < imageSource.getHeight(); y += stepY, destY++) {
                    dest.setRGB(destX, destY, imageSource.getRGB(x, y));
                }
                destY = 0;
            }
            imageTrueDest = dest;
            BufferedImage visible = new BufferedImage(dest.getWidth() * stepX, dest.getHeight() * stepY, BufferedImage.TYPE_INT_ARGB);
            Graphics2D g = (Graphics2D)visible.getGraphics();
            g.scale(stepX, stepY);
            g.drawImage(dest, null, 0, 0);
            imageDest = visible;
            panelDest.setImage(imageDest);
        }
    }//GEN-LAST:event_btnPixelizeActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        String text = "For recovering lost pixel art, from a screenshot.  Or for pixelizing images.\n"
                + "Here's what you do.\n"
                + "1. Take a screenshot of the art, as clear of error dialogs as possible.\n"
                + "2. Optionally trim down to just around the image.  As long as there's still more\n"
                + "       than half a \"pixel\" left on the outer edge, it should be fine.\n"
                + "3. Open the image here.\n"
                + "4. Adjust parameters, and click Pixelize.  Repeat until it looks right.\n"
                + "If you need scrollbars and they're missing, try resizing the window slightly.\n"
                + "5. Save.  Note that it will be a PNG, regardless of your filename, so save it as a png.\n"
                + "Also: each large pixel will be saved as a small pixel (you'll end up with a small image).\n"
                + "6. Optionally edit it with GIMP or something to clean up remaining glitches, or rescale it.\n"
                + "\n"
                + "- Erhannis, 2015";
        JOptionPane.showMessageDialog(this, text);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PARMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PARMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PARMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PARMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PARMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPixelize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JMenuItem mitemOpenSource;
    private javax.swing.JMenuItem mitemSaveDest;
    private javax.swing.JSpinner spinOffsetX;
    private javax.swing.JSpinner spinOffsetY;
    private javax.swing.JSpinner spinStepX;
    private javax.swing.JSpinner spinStepY;
    // End of variables declaration//GEN-END:variables
}
